/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Analytics } from "./Analytics";
import { AnalyticsCountArgs } from "./AnalyticsCountArgs";
import { AnalyticsFindManyArgs } from "./AnalyticsFindManyArgs";
import { AnalyticsFindUniqueArgs } from "./AnalyticsFindUniqueArgs";
import { CreateAnalyticsArgs } from "./CreateAnalyticsArgs";
import { UpdateAnalyticsArgs } from "./UpdateAnalyticsArgs";
import { DeleteAnalyticsArgs } from "./DeleteAnalyticsArgs";
import { AnalyticsService } from "../analytics.service";
@graphql.Resolver(() => Analytics)
export class AnalyticsResolverBase {
  constructor(protected readonly service: AnalyticsService) {}

  async _analyticsItemsMeta(
    @graphql.Args() args: AnalyticsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Analytics])
  async analyticsItems(
    @graphql.Args() args: AnalyticsFindManyArgs
  ): Promise<Analytics[]> {
    return this.service.analyticsItems(args);
  }

  @graphql.Query(() => Analytics, { nullable: true })
  async analytics(
    @graphql.Args() args: AnalyticsFindUniqueArgs
  ): Promise<Analytics | null> {
    const result = await this.service.analytics(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Analytics)
  async createAnalytics(
    @graphql.Args() args: CreateAnalyticsArgs
  ): Promise<Analytics> {
    return await this.service.createAnalytics({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Analytics)
  async updateAnalytics(
    @graphql.Args() args: UpdateAnalyticsArgs
  ): Promise<Analytics | null> {
    try {
      return await this.service.updateAnalytics({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Analytics)
  async deleteAnalytics(
    @graphql.Args() args: DeleteAnalyticsArgs
  ): Promise<Analytics | null> {
    try {
      return await this.service.deleteAnalytics(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
